import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "./components/header";
import Footer from "./components/footer";

export default function Home() {
  return (
    <div className="container mx-auto lg:px-8 md:px-6 px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="mt-12 md:mt-20 md:flex flex-row-reverse mb-10">
          <div>
            <Image
              src="/group-23.png"
              alt="Picture of the author"
              width={597}
              height={442}
            />
          </div>
          <div className="mt-8 md:mt-0 flex-auto text-center md:text-left">
            <h1 className="text-dark text-7xl2 md:text-8xl2 font-extrabold leading-68 md:leading-88">
              SOC 2
            </h1>
            <h2 className="text-dark font-extrabold text-base3 md:text-4xl2 leading-34 md:leading-44">
              for fast moving SaaS companies
            </h2>
            <p className="text-base2 leading-6 py-4 md:py-2 text-medium">
              Use Sprinto to obtain SOC 2 compliance, close enterprise deals
              faster, and pass vendor security assessments with ease.
            </p>
            <Footer />
          </div>
        </div>
      </main>
    </div>
  );
}
